### ISSUE TITLE
Code in Mona is not the best

### ISSUE THREAD

**Issue by nikitasakau** [datarockets/mona#68]
* [x] [Add Github actions](https://github.com/datarockets/mona/pull/69)
* [x] [Add ESLint](https://github.com/datarockets/mona/issues/71)
* [x] Check and merge dependencies' PRs
* [ ] Update README with actual information and dev tips
* [x] Remove `.DS_Store` from gitignore, because it's related to local machine, not project
* [ ] `bot.js` file is overwhelming, need to split into helpers?, maybe separate file for each action?
* [x] All files should be named with camelCase, not snake_case
* [ ] #61 Think about tests refactoring

**Comment by lazycoder9** [comment]
I don't like `module.exports` and `require` in code. I prefer to use import/export syntax. I suggest that we can use latest node on heroku to use this syntax. I can make some investigation if it is possible to use latest node in heroku

**Comment by lazycoder9** [comment]
>use the `engines` section of your `package.json` to specify the version of Node.js to use on Heroku. Drop the ‘v’ to save only the version number:
```javascript
{
  "name": "myapp",
  "description": "a really cool app",
  "version": "1.0.0",
  "engines": {
    "node": "12.13.0"
  }
}
```

**Comment by lazycoder9** [comment]
I was able to use `import` and `export` in code with Node v13.2 locally

**Comment by lazycoder9** [comment]
@npupko @nikitasakov what do you think about setting up Github actions? Sounds reasonable if you want to set up linter too

**Comment by npupko** [comment]
@lazycoder9 Is it (setup) faster than other CI services? 
How much time will we need to enable it from scratch?
Didn't work with it before.

**Comment by lazycoder9** [comment]
@npupko it took me about 30 minutes to learn about it and 5 minutes to implement it in docker_benchmark repo 😄

**Comment by npupko** [comment]
@lazycoder9 This is what we need then:)

**Comment by AleksSenkou** [comment]
Gyus, I'd suggest keeping a checklist in issue's description to know what is left, easier to manage

All of you should have access to edit the description 😉

**Comment by npupko** [comment]
Dudes, how about using `yarn` instead of `npm`?

**Comment by lazycoder9** [comment]
@npupko @nikitasakov Also, I want to move from mocha to jest. Thoughts?

**Comment by npupko** [comment]
@lazycoder9 Mocks out of the box and rspec-similar syntax. I like it.
 But is it worth the time?

**Comment by lazycoder9** [comment]
@npupko refreshed my knowledge about jest yesterday and I don't think that it is worth our effort currently to move to jest
